dependencies:
- name: composite-team-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- name: core-player-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.39
- name: core-team-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.104
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
